name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar tu código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker para construir la imagen
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Construir y enviar la imagen a Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-devops-test:latest

      # 5. Mostrar el resultado
      - name: Show Image Digest
        run: echo "Proceso exitoso!"
